build:
    environment:
        php:
            version: 5.6
            
checks:
    php:
        code_rating: true
        duplication: true
filter:
    excluded_paths:
        - vendor/*
        - tests/*     
tools:
    external_code_coverage:
        timeout: 600
